---
Kind: Deployment
apiVersion: apps/v1
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: blog
        image: blog:latest
        ports:
        - containerPort: 80
---
Kind: Service
apiVersion: v1
metadata:
  name: blog
  labels:
    app: blog
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: blog
---
Kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: blog
  labels:
    app: blog
spec:
  rules:
  - host: blog.huemie.space
    http:
      paths:
        